// /* Create a business name generator by combining list of adjectives and shop name and another word
// Adjectives:
// Crazy 
// Amazing
// Fire 

// Shop Name:
// Engine
// Foods
// Garments

// Another Word:
// Bros
// Limited
// Hub
// */

// let adjectives = ["Crazy", "Amazing", "Fire"];
// let shopNames = ["Engine", "Foods", "Garments"];
// let anotherWords = ["Bros", "Limited", "Hub"];
// function generateBusinessName() {
//     let randomAdjective = adjectives[Math.floor(Math.random() * adjectives.length)];
//     let randomShopName = shopNames[Math.floor(Math.random() * shopNames.length)];
//     let randomAnotherWord = anotherWords[Math.floor(Math.random() * anotherWords.length)];
//     return `${randomAdjective} ${randomShopName} ${randomAnotherWord}`;

// }
// console.log(generateBusinessName());

/* 
here math.floor() is used to round down the random number generated by math.random() to the nearest whole number, 
which is then used as an index to select a random element from the arrays of adjectives, shop names, and another words. 
The function generateBusinessName() combines these randomly selected elements into a business name and returns it. 
Finally, we log the generated business name to the console.

We multiply Math.random() by the length of the respective array to ensure that the random index falls within the valid range of indices for that array.

Math.random() gives a decimal number between 0 and 1  where 1 is excluded
eg: 0.12
0.87
0.45
0.999
It will never be 1
it starts feom 0 to 1 exclusive of 1
Suppose our array is : let adjectives = ["Crazy", "Amazing", "Fire"];
length = 3
multiply with length
math.random() * adjectives.length
0.12 * 3 = 0.36
0.87 * 3 = 2.61
0.45 * 3 = 1.35
0.999 * 3 = 2.997
range 0 to 2.997
math.floor() will round down the number to the nearest whole number
0.36 will become 0
2.61 will become 2
1.35 will become 1
2.997 will become 2
final pssoible index will be 0, 1, or 2 which corresponds to the elements in the adjectives array.
use adjectuve index to get the adjective
if index is 0 then adjective will be "Crazy"
if index is 1 then adjective will be "Amazing"
if index is 2 then adjective will be "Fire"
same process is applied to shopNames and anotherWords arrays to get random shop name and another word.

*/
//  without using array we can do:

function generateBusinessName() {
    let rand1 = Math.floor(Math.random() * 3);
    let ran2 = Math.floor(Math.random() * 3);
    let ran3 = Math.floor(Math.random() * 3);
    let adjective;
    let shopName;
    let anotherWord;
    if (rand1 ===0)
        adjective = "Crazy";
    else if (rand1 ===1)
        adjective = "Amazing";
    else
        adjective = "Fire";

    if (ran2 ===0)
        shopName = "Engine";
    else if (ran2 ===1)
        shopName = "Foods";
    else
        shopName = "Garments";

    if (ran3 ===0)
        anotherWord = "Bros";
    else if (ran3 ===1)
        anotherWord = "Limited";
    else
        anotherWord = "Hub";

    return adjective + " " + shopName + " " + anotherWord; 
}
console.log(generateBusinessName());
